# This is a basic workflow to help you get started with Actions

name: RUN Scraper

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"
        # Installs Python
      - uses: actions/setup-python@v3
        with:
          python-version: "3.7" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - name: rclone-action-integration
        run : |
          sudo apt install rclone
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          node -v
          npm run setup
          
        # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          npm run single https://demos-europe-west2.faceit-cdn.net/csgo/1-4ae0e998-bd3e-47b0-935c-5da09438614d-1-1.dem.gz
      
      # Runs a set of commands using the runners shell
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: somethingCool
          # A file, directory or wildcard pattern that describes what to upload
          path: dist/** 
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
          retention-days: 1
